FROM biodatageeks/cnv-opt-codex
MAINTAINER biodatageeks <team@biodatageeks.ii.pw.edu.pl>

ARG CACHE_DATE=not_a_date

RUN Rscript -e "install.packages('TARGET.QC', repos = 'http://zsibio.ii.pw.edu.pl/nexus/repository/r-all')"
