FROM biodatageeks/cnv-opt-exomedepth
MAINTAINER biodatageeks <team@biodatageeks.ii.pw.edu.pl>

RUN Rscript -e "install.packages('EXOMEDEPTHCOV', repos = 'http://zsibio.ii.pw.edu.pl/nexus/repository/r-all')"

